### ISSUE TITLE
Slew of errors

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/benson#12]
Notice: Undefined variable: paginate in /srv/www/testing-grounds/htdocs/wp-content/plugins/benson/public/class-benson-public.php on line 157

Notice: Undefined variable: sanitize in /srv/www/testing-grounds/htdocs/wp-content/plugins/benson/public/class-benson-public.php on line 158

Notice: Undefined variable: filter in /srv/www/testing-grounds/htdocs/wp-content/plugins/benson/public/class-benson-public.php on line 160

**Comment by streeetlamp** [comment]
fixed https://github.com/VCUarts/benson/commit/f9b5505ee530031e9b31cfdcee0b2dd6c7f0096d
