### ISSUE TITLE
update names and stuff in the plugin

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/benson#2]
so much generic use of 'plugin-name' etc

need to figure out proper way of resolving that mess with having to manually change that junk everywhere

**Comment by luetkemj** [comment]
use this: http://wppb.me/

**Comment by streeetlamp** [comment]
u da bes, u deed it 
![2c7ixq8](https://cloud.githubusercontent.com/assets/1740634/6471134/9456313a-c1b6-11e4-9145-df2c0f8e2c00.gif)
