### ISSUE TITLE
Only enqueue frontend scripts if we have need them

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/benson#4]
check if we have pasted an endpoint. If we have - great use it.
Otherwise no.

Would there be any value to checking for handlebar markup??? Possibly on single posts or archives or something? Checking for need could get complicated

**Comment by streeetlamp** [comment]
if no endpoint meta value is set don't enqueue anything 

![tumblr_nko3ucb0et1sbvpf3o1_400](https://cloud.githubusercontent.com/assets/1740634/6488885/79da3650-c268-11e4-90f3-15f1a2ce2165.gif)
